### ISSUE TITLE
Transfer website to mynt from readymag

### ISSUE THREAD

**Issue by nazarov-tech** [pyladies-spb/pyladysite#1]
[feature/1-static-generator](https://github.com/pyladies-spb/pyladysite/tree/feature/1-static-generator)

**Comment by nazarov-tech** [comment]
поковырял pelican: https://i.imgur.com/uqmSMaa.png

Геморно будет тему подпилить под вёрстку + выпилить из него блоггинг.

Предлагаю брать штатный генератор PyLadies (минт) и не париться, даром что Python 2 (увы).

**Comment by lilislilit** [comment]
посолвлено в #2

**Comment by nazarov-tech** [comment]
test..
